name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad83a33532d93bdc6203e7cdf2c1eee5b5d77e5cc8f8fc28f62df1c993e35ffd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
