name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd2def5c8213fc99ff00e46c6c8b5aad72568917ae3d26e0d6b8c66e89d619b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
