name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "979da9c7e3d25b62b8af6524ccda01b8096dc5408d67f72ec0a5313ab90d0a8a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
