name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc681b56b0ba07d1df62f7e9cc085a08fcfd2296329735eb4166ecc9d099ca7a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
