name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d15e112470576192bda9ae270efb9875e0b752f72536d7b9fedfdbab3c2245a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
