name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e821153d40c4fbca152befe2d1eba894405deb5a7ab6672c937cd17d580647ed"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
