name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8d1c622da6658e284f43923c4a6f4c353460f7daff387b84242a042ca3a5235"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
