name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74898e1b1e2afa39ddda5f3dafcdbb0190f10d27aeb9396da03551a7ae3cbab3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
