name = "Circus"
author = "Danny Le"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "149a2768b94bfc8d5b6164176c9501dfe074b0ffda77142ac79a0cab2faae9e3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
